"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var health_1 = require("./health");
var auth_1 = require("./auth");
var users_1 = require("./users");
var subscriptions_1 = require("./subscriptions");
var features_1 = require("./features");
var graphs_1 = require("./graphs");
var usage_1 = require("./usage");
var billing_1 = require("./billing");
var admin_1 = require("./admin");
var notifications_1 = require("./notifications");
var chat_1 = require("./chat");
var router = (0, express_1.Router)();
router.use(health_1.default);
router.use("/auth", auth_1.default);
router.use("/users", users_1.default);
router.use("/subscriptions", subscriptions_1.default);
router.use("/features", features_1.default);
router.use("/graphs", graphs_1.default);
router.use("/usage", usage_1.default);
router.use("/billing", billing_1.default);
router.use("/admin", admin_1.default);
router.use("/notifications", notifications_1.default);
router.use("/chat", chat_1.default);
exports.default = router;
